Ignite APIs and several properties to ZCRMAttachment added
zoho/CRM-iOSSDK pull request #16
Opened 2018-08-31 13:51 UTC by UmashriR

2018-09-01 12:52 UTC, BoopathyPSiva commented on ZCRMiOS/Classes/ModuleAPIHandler.swift
> +            if let bulkResponse = response
use guard instead of if let

2018-09-01 12:56 UTC, BoopathyPSiva reviewed
Use guard instead of if let.
Response nil error isn't handled.

2018-09-04 17:05 UTC, BoopathyPSiva commented on ZCRMiOS/Classes/MassEntityAPIHandler.swift
> +            if( ResponseParamKeys.deletedBy == fieldAPIName )
ResponseParamKeys.createdBy

2018-09-04 17:06 UTC, BoopathyPSiva commented on ZCRMiOS/Classes/MassEntityAPIHandler.swift
> +            else if( ResponseParamKeys.createdBy == fieldAPIName )
It should be ResponseParamKeys. deletedBy

2018-09-04 17:19 UTC, BoopathyPSiva commented on ZCRMiOS/Classes/TagAPIHandler.swift
> +            else
remove else. else is not needed here

2018-09-04 17:19 UTC, BoopathyPSiva commented on ZCRMiOS/Classes/TagAPIHandler.swift
> +                    if let response = resp
use guard here

2018-09-04 17:21 UTC, BoopathyPSiva commented on ZCRMiOS/Classes/TagAPIHandler.swift
> +                conflictIdJSON[RequestParamKeys.conflictId] = conflictTagJSON[ResponseParamKeys.id]
remove else. else is not needed here

2018-09-04 17:51 UTC, BoopathyPSiva approved these changes

2018-09-05 06:51 UTC, vijayakrishnap requested changes

2018-09-05 06:51 UTC, vijayakrishnap commented on ZCRMiOS/Classes/ZCRMOrganisation.swift
> +    public func searchUserByCriteria( criteria : String, completion : @escaping( [ ZCRMUser ]?, BulkAPIResponse?, Error? ) -> () )
have method name as "searchUsers" and label for first argument as "withCriteria"

2018-09-05 07:18 UTC, vijayakrishnap approved these changes

2018-09-05 07:18 UTC, merged