Timeline API added and issues in notes and attachment fixed
zoho/CRM-iOSSDK pull request #28
Opened 2018-10-03 13:44 UTC by UmashriR

Issue in notes and attachment fixed

2018-10-03 18:23 UTC, BoopathyPSiva commented on ZCRMiOS/Classes/CommonUtil.swift
> -}
Why did you remove CommonUtil.Swift file?

2018-10-03 18:26 UTC, BoopathyPSiva commented on ZCRMiOS/Classes/EntityAPIHandler.swift
> +        setUrlPath(urlPath: "/\(self.recordDelegate.moduleAPIName)/\(self.recordDelegate.recordId)/timelines")
check recordDelegate has recordId.

2018-10-03 18:28 UTC, BoopathyPSiva commented on ZCRMiOS/Classes/EntityAPIHandler.swift
> +                if responseJSON.isEmpty == false
else must throw an error.

2018-10-03 18:29 UTC, BoopathyPSiva commented on ZCRMiOS/Classes/EntityAPIHandler.swift
> +                    self.setParticipants( participantsArray : value as! [ [ String : Any ] ] )
Don't do force unwrap.

2018-10-03 18:30 UTC, BoopathyPSiva commented on ZCRMiOS/Classes/EntityAPIHandler.swift
> +        if timelineDetails.hasValue(forKey: "audited_time") == false
"audited_time", "action" should be added in ResponseJSON keys

2018-10-03 18:33 UTC, BoopathyPSiva commented on ZCRMiOS/Classes/RelatedListAPIHandler.swift
> +                                try EntityAPIHandler(record: record).setRecordProperties(recordDetails: recordDetails)
"Activities", "Activity_Type" should be added in ResponseJSON keys.

2018-10-03 18:35 UTC, BoopathyPSiva commented on ZCRMiOS/Classes/ZCRMNote.swift
> +        for count in 0..<self.attachments!.count - 1
Don't use force unwrap.

2018-10-03 18:36 UTC, BoopathyPSiva commented on ZCRMiOS/Classes/ZCRMNote.swift
>              completion( result )
completion should be in do block.

2018-10-03 18:36 UTC, BoopathyPSiva commented on ZCRMiOS/Classes/ZCRMNote.swift
>              completion( result )
completion should be in the do block.

2018-10-03 18:38 UTC, BoopathyPSiva commented on ZCRMiOS/Classes/ZCRMNote.swift
> +                self.removeAttachment(attachmentId: attachmentId)
add response status check before removing the attachment in attachment array.

2018-10-03 18:41 UTC, BoopathyPSiva commented on ZCRMiOS/Classes/ZCRMOrganisationDelegate.swift
> +    public func newRole(name: String) -> ZCRMRole
Is it necessary?

2018-10-03 18:41 UTC, BoopathyPSiva commented on ZCRMiOS/Classes/ZCRMOrganisationDelegate.swift
> +    public func newProfile( name : String ) -> ZCRMProfile
Is it necessary?

2018-10-03 18:42 UTC, BoopathyPSiva commented on ZCRMiOS/Classes/ZCRMStageDelegate.swift
> +//
why did you add this file?

2018-10-04 09:59 UTC, BoopathyPSiva commented on ZCRMiOS/Classes/EntityAPIHandler.swift
> +        timeline.automationRule = timelineDetails.optDictionary(key: ResponseJSONKeys.automationDetails)?.optDictionary(key: ResponseJSONKeys.rule)?.optString(key: ResponseJSONKeys.name)
Why do you fetch automation details dictionary two times?

2018-10-05 09:42 UTC, BoopathyPSiva commented on ZCRMiOS/Classes/MassEntityAPIHandler.swift
> +                        bulkResponse.setData( data : updatedRecords )
Revert this change.

2018-10-06 11:13 UTC, vijayakrishnap requested changes

2018-10-06 11:13 UTC, vijayakrishnap commented on ZCRMiOS/Classes/ZCRMModuleDelegate.swift
> +        return ZCRMCustomView(cvName: cvName, moduleAPIName: self.apiName)
This should hit request to return fully filled ZCRMCustomView object right?
If something will return an object without hitting request, it should return only delegate object.

2018-10-08 12:55 UTC, vijayakrishnap approved these changes

2018-10-08 12:55 UTC, merged