User uma
zoho/CRM-iOSSDK pull request #6
Opened 2018-08-02 14:45 UTC by UmashriR

- Tags API added
- Field and Module unwanted properties removed and added few properties
- Method for get a field added
- Converted record supported module handling(Leads)
- Changed Trash Record key name from Created_by to created_by
- Added fields APIs rounding option as enum (round_off, round_down, round_up and normal)
- Parent Record Id for Add Note for a record added

2018-08-03 04:06 UTC, vijayakrishnap requested changes
@UmashriR  @BoopathyPSiva

2018-08-03 04:06 UTC, vijayakrishnap commented on ZCRMiOS/Classes/MassEntityAPIHandler.swift
> +            if( "created_By" == fieldAPIName )
Shouldn't this be Created_By ?

2018-08-03 04:06 UTC, vijayakrishnap commented on ZCRMiOS/Classes/ZCRMTag.swift
> +    public func mergeTags( conflictId : Int64, completion : @escaping ( ZCRMTag?, APIResponse?, Error? ) -> () )
Where to get this conflictId?

2018-08-03 04:06 UTC, vijayakrishnap commented on ZCRMiOS/Classes/ZCRMRecord.swift
> +    public func addTags( module : ZCRMModule, params : [String], values : [Any], completion : @escaping ( ZCRMTag?, APIResponse?, Error? ) -> () )
Why module argument here when record has a module property?

2018-08-03 04:06 UTC, vijayakrishnap commented on ZCRMiOS/Classes/ZCRMRecord.swift
> +    public func removeTags( module : ZCRMModule, params : [String], values : [Any], completion : @escaping ( ZCRMTag?, APIResponse?, Error? ) -> () )
What is this argument params?

2018-08-03 04:06 UTC, vijayakrishnap commented on ZCRMiOS/Classes/ZCRMModule.swift
> +    private var arguments : [ String : Any ]?
What is this property "arguments" ?

2018-08-03 04:06 UTC, vijayakrishnap commented on ZCRMiOS/Classes/ZCRMModule.swift
> +    public func updateTags(tagIds : [Int64], names : [String], completion : @escaping ( [ZCRMTag]?, BulkAPIResponse?, Error? ) -> () )
Why not get an array of ZCRMTags to update this instead of 2 arrays of ids and names ?

2018-08-03 04:06 UTC, vijayakrishnap commented on ZCRMiOS/Classes/ZCRMModule.swift
> +    public func addTags( recordIds : [Int64], params : [String], values : [Any], completion : @escaping ( [ZCRMTag]?, BulkAPIResponse?, Error? ) -> () )
What do the arguments params and values mean?

2018-08-03 04:06 UTC, vijayakrishnap commented on ZCRMiOS/Classes/TagAPIHandler.swift
> +    internal func addTags( recordId : Int64, params : [String], values : [Any], completion : @escaping( ZCRMTag?, APIResponse?, Error? ) -> () )
Move these to EntityAPIHandler since this is hitting record APIs and not Tag APIs.

2018-08-03 09:45 UTC, UmashriR commented on ZCRMiOS/Classes/ZCRMTag.swift
> +    public func mergeTags( conflictId : Int64, completion : @escaping ( ZCRMTag?, APIResponse?, Error? ) -> () )
User will provide the conflict id as a parameter to the method

2018-08-03 10:44 UTC, UmashriR commented on ZCRMiOS/Classes/TagAPIHandler.swift
> +    internal func addTags( recordId : Int64, params : [String], values : [Any], completion : @escaping( ZCRMTag?, APIResponse?, Error? ) -> () )
All Tag APIs are grouped under TagAPIHandler

2018-08-03 10:51 UTC, UmashriR commented on ZCRMiOS/Classes/ZCRMModule.swift
> +    public func updateTags(tagIds : [Int64], names : [String], completion : @escaping ( [ZCRMTag]?, BulkAPIResponse?, Error? ) -> () )
Changes made

2018-08-03 10:52 UTC, UmashriR commented on ZCRMiOS/Classes/ZCRMRecord.swift
> +    public func addTags( module : ZCRMModule, params : [String], values : [Any], completion : @escaping ( ZCRMTag?, APIResponse?, Error? ) -> () )
Changes made

2018-08-03 10:53 UTC, UmashriR commented on ZCRMiOS/Classes/MassEntityAPIHandler.swift
> +            if( "created_By" == fieldAPIName )
No, they have changed the response

2018-08-06 07:23 UTC, vijayakrishnap commented
Lets support module.createTag(ZCRMTag) and module.updateTag(ZCRMTag) also. Let this methods blindly call module.createTags([ZCRMTag]) with single array element.

2018-08-06 07:23 UTC, vijayakrishnap requested changes

2018-08-06 07:23 UTC, vijayakrishnap commented on ZCRMiOS/Classes/ZCRMTag.swift
> +    public func mergeTags( conflictTag : ZCRMTag, completion : @escaping ( ZCRMTag?, APIResponse?, Error? ) -> () )
change this method signature as 
merge(anotherTag : ZCRMTag, ..... )

2018-08-06 07:23 UTC, vijayakrishnap commented on ZCRMiOS/Classes/ZCRMTag.swift
> +    public func updateTag( updateTag : ZCRMTag, module : ZCRMModule, completion : @escaping ( ZCRMTag?, APIResponse?, Error? ) -> () )
Change this method name to just "update", since this is already inside the tag object.

2018-08-06 13:36 UTC, vijayakrishnap commented on ZCRMiOS/Classes/ZCRMTag.swift
> +    public func mergeTags( conflictTag : ZCRMTag, completion : @escaping ( ZCRMTag?, APIResponse?, Error? ) -> () )
@UmashriR  Think this is not done.

2018-08-07 06:27 UTC, vijayakrishnap approved these changes

2018-08-07 06:28 UTC, merged